import type { Product, CategoryInfo, Partner } from "@/types";
import { env } from "./env";

export const CATEGORIES: CategoryInfo[] = [
  {
    slug: "gear-damper",
    name: "Gear Dampers",
    description: "Compact rotary control for cup holders, lids and storage doors.",
    image: "/images/products/gear-damper/GearDamperCategory.webp",
  },
  {
    slug: "axial-damper",
    name: "Axial Dampers",
    description: "Linear damping for controlled opening, closing and sliding motion.",
    image: "/images/products/axial-damper/AxialDamperCategory.webp",
  },
  {
    slug: "glove-box-damper",
    name: "Glove Box Dampers",
    description: "Automotive soft motion for glove boxes and interior panels.",
    image: "/images/products/glove-box-damper/GloveBoxDamperCategory.webp",
  },
  {
    slug: "latch",
    name: "Latches",
    description: "Reliable lock, release and engagement mechanisms for interiors.",
    image: "/images/products/latch/LatchCategory.webp",
  },
  {
    slug: "other",
    name: "Other Products",
    description: "Organizers, custom modules and application-specific mechanisms.",
    image: "/images/products/other/OthersCategory.webp",
  },
];

export const PRODUCTS: Product[] = [
  {
    slug: "trd-25-rotary-gear-damper",
    model: "TRD-25",
    name: "TRD-25 Rotary Gear Damper",
    category: "gear-damper",
    summary: "High-torque rotary damper for automotive interior applications.",
    description:
      "The TRD-25 series provides smooth, controlled rotary motion for automotive interior applications including cup holders, storage compartments, and assist handles. Available in multiple torque ranges with customizable mounting configurations.",
    image: "/images/products/gear-damper/GearDamperSingle.webp",
    images: [],
    specifications: {
      "Torque Range": "0.5 – 4.0 N·m",
      "Operating Temperature": "-30°C to +80°C",
      "Material": "POM / PA66 + GF",
      "Damping Direction": "Clockwise / Counter-clockwise / Both",
      "Life Cycle": ">50,000 cycles",
    },
    features: [
      "Compact design fits tight interior spaces",
      "Stable torque output across temperature range",
      "Custom torque values available",
      "Low noise operation",
    ],
    applications: ["Automotive interiors", "Storage compartments"],
    isActive: true,
    sortOrder: 1,
  },
  {
    slug: "rd-t015",
    model: "RD-T015",
    name: "Gear Damper RD-T015",
    category: "gear-damper",
    summary: "SOC-free rotary gear damper with bidirectional damping for automotive interior mechanisms.",
    description:
      "The RD-T015 is a compact rotary gear damper engineered for controlled deceleration in automotive interior applications including cup holders, storage compartments, door handles, and assist grips. SOC-free silicone oil provides consistent torque output across a wide temperature range, with screw-mount installation and no angular limit.",
    image: "/images/product-list/Gear-damper/RD-T015/RD-T015-product-01.webp",
    images: [
      { url: "/images/product-list/Gear-damper/RD-T015/RD-T015-product-01.webp", alt: "RD-T015 gear damper front view" },
      { url: "/images/product-list/Gear-damper/RD-T015/RD-T015-product-02.webp", alt: "RD-T015 gear damper angled view" },
      { url: "/images/product-list/Gear-damper/RD-T015/RD-T015-product-03.webp", alt: "RD-T015 gear damper side view" },
      { url: "/images/product-list/Gear-damper/RD-T015/RD-T015-product-04.webp", alt: "RD-T015 gear damper detail view" },
    ],
    features: [],
    characteristics: ["SOC Free", "Screw mounting", "Two-way", "No angle limit"],
    dimension_drawing: "/images/product-list/Gear-damper/RD-T015/dimension.webp",
    performance_charts: {
      rotation_curve: "/images/product-list/Gear-damper/RD-T015/rotation-curve.webp",
      temperature_curve: "/images/product-list/Gear-damper/RD-T015/temperature-curve.webp",
    },
    torque: { min: 50, max: 500, unit: "gf.cm" },
    tech_params: {
      teeth_count: 11,
      module: 0.8,
      outer_diameter: "Φ14.7",
      pressure_angle: 20,
    },
    specifications: {
      "Model": "RD-T015",
      "Torque Range": "50 – 500 gf·cm",
      "Operating Temperature": "-30°C to +80°C",
      "Damping Direction": "Bidirectional (Two-way)",
      "Mounting Method": "Screw fixing",
      "Angle Limit": "None (360° free rotation)",
      "Damping Oil": "SOC-free silicone oil",
      "Life Cycle": ">30,000 cycles",
    },
    materials: [
      { part: "Housing", material: "POM (Polyoxymethylene)" },
      { part: "Cap / Cover", material: "POM" },
      { part: "O-ring Seal", material: "Silicone rubber" },
      { part: "Gear Rotor", material: "PA66 + GF (30% glass-filled)" },
      { part: "Damping Fluid", material: "SOC-free silicone oil" },
      { part: "Screw", material: "Stainless steel (SUS304)" },
    ],
    buffer_direction: "bidirectional",
    assembly_method: "Screw Fixing",
    durability: {
      temperature: "-30°C to +80°C",
      cycles: 30000,
      cycles_unit: "cycles",
    },
    applications: [
      "Automotive interiors",
      "Cup holders",
      "Glove boxes",
      "Center console lids",
      "Storage compartments",
      "Door handles",
      "Outlet covers",
      "Ashtrays",
      "Bathroom fittings",
      "Toilet lids",
    ],
    isActive: true,
    sortOrder: 2,
  },
  {
    slug: "rd-t021",
    model: "RD-T021",
    name: "Gear Damper RD-T021",
    category: "gear-damper",
    summary: "Applicable to automotive interior and exterior fittings as well as office equipment.",
    description:
      "The RD-T021 gear damper provides smooth rotary damping for automotive interior and exterior applications. Compact design with customizable torque output within standard ranges.",
    image: "/images/products/gear-damper/GearDamperSingle.webp",
    images: [],
    tech_params: { teeth_count: 11, module: 0.8, pressure_angle: 20 },
    specifications: {
      "Torque Range": "20 – 300 gf·cm",
      "Operating Temperature": "-30°C to +80°C",
      "Material": "POM / PA66 + GF",
      "Damping Direction": "One-way",
    },
    features: [
      "Compact rotary damper",
      "Screw-fit mounting",
      "Stable torque output",
      "Low noise operation",
    ],
    torque: { min: 20, max: 300, unit: "gf.cm" },
    assembly_method: "Screw Fixing",
    buffer_direction: "bidirectional",
    durability: { cycles: 30000, cycles_unit: "cycles" },
    applications: ["Automotive interior", "Exterior fittings", "Office equipment"],
    isActive: true,
    sortOrder: 3,
  },
  {
    slug: "rd-t069",
    model: "RD-T069",
    name: "Bidirectional Gear Damper RD-T069 / RD-V069",
    category: "gear-damper",
    summary:
      "Bidirectional type, suitable for automotive interiors, household appliances, and industrial machinery.",
    description:
      "The RD-T069 / RD-V069 bidirectional gear damper provides controlled rotary damping in both directions. Ideal for applications requiring smooth motion in both opening and closing directions.",
    image: "/images/products/gear-damper/GearDamperSingle.webp",
    images: [],
    tech_params: { teeth_count: 12, module: 0.8, outer_diameter: "Φ14.7", pressure_angle: 20 },
    specifications: {
      "Torque Range": "200 – 3,500 gf·cm",
      "Operating Temperature": "-30°C to +80°C",
      "Damping Direction": "Bidirectional",
    },
    features: [
      "Bidirectional damping",
      "Screw-fit mounting",
      "High torque output",
      "Industrial-grade durability",
    ],
    torque: { min: 200, max: 3500, unit: "gf.cm" },
    assembly_method: "Screw Fixing",
    buffer_direction: "bidirectional",
    durability: { cycles: 30000, cycles_unit: "cycles" },
    applications: ["Automotive interiors", "Household appliances", "Industrial machinery"],
    isActive: true,
    sortOrder: 4,
  },
  {
    slug: "rd-t040",
    model: "RD-T040",
    name: "Gear Damper RD-T040",
    category: "gear-damper",
    summary:
      "Applicable to automotive dampers, household appliance dampers, plastic gear dampers, and buffer components.",
    description:
      "The RD-T040 gear damper delivers consistent rotary damping for automotive, appliance, and industrial buffer applications. Compact size with reliable screw-fit mounting.",
    image: "/images/products/gear-damper/GearDamperSingle.webp",
    images: [],
    tech_params: { teeth_count: 10, module: 0.8, outer_diameter: "Φ10.4", pressure_angle: 20 },
    specifications: {
      "Torque Range": "20 – 300 gf·cm",
      "Operating Temperature": "-30°C to +80°C",
    },
    features: [
      "Compact Φ10.4 size",
      "Screw-fit mounting",
      "Consistent torque profile",
      "Multi-industry compatible",
    ],
    torque: { min: 20, max: 300, unit: "gf.cm" },
    assembly_method: "Screw Fixing",
    buffer_direction: "bidirectional",
    durability: { cycles: 20000, cycles_unit: "cycles" },
    applications: ["Automotive dampers", "Household appliances", "Plastic gear buffers"],
    isActive: true,
    sortOrder: 5,
  },
  {
    slug: "rd-t036",
    model: "RD-T036",
    name: "Gear Damper RD-T036",
    category: "gear-damper",
    summary: "Applicable to automotive interiors, household appliances, and industrial machinery.",
    description:
      "The RD-T036 gear damper provides high-torque rotary damping with a Φ13 size and 1.2 module. Suitable for automotive interiors, appliances, and industrial applications requiring higher damping force.",
    image: "/images/products/gear-damper/GearDamperSingle.webp",
    images: [],
    tech_params: { teeth_count: 13, module: 1.2, outer_diameter: "Φ13", pressure_angle: 20 },
    specifications: {
      "Torque Range": "20 – 1,000 gf·cm",
      "Operating Temperature": "-30°C to +80°C",
    },
    features: [
      "High torque capacity (up to 1,000 gf·cm)",
      "Φ13 size with 1.2 module",
      "Screw-fit mounting",
      "Versatile application range",
    ],
    torque: { min: 20, max: 1000, unit: "gf.cm" },
    assembly_method: "Screw Fixing",
    buffer_direction: "bidirectional",
    durability: { cycles: 20000, cycles_unit: "cycles" },
    applications: ["Automotive interiors", "Household appliances", "Industrial machinery"],
    isActive: true,
    sortOrder: 6,
  },
  {
    slug: "rd-t029",
    model: "RD-T029",
    name: "Gear Damper RD-T029",
    category: "gear-damper",
    summary: "Applicable to automotive interiors, household appliances, and industrial machinery.",
    description:
      "The RD-T029 gear damper is a compact Φ10.4 rotary damper with 0.8 module. Designed for space-constrained applications in automotive interiors, household appliances, and industrial machinery.",
    image: "/images/products/gear-damper/GearDamperSingle.webp",
    images: [],
    tech_params: { teeth_count: 10, module: 0.8, outer_diameter: "Φ10.4", pressure_angle: 20 },
    specifications: {
      "Torque Range": "20 – 300 gf·cm",
      "Operating Temperature": "-30°C to +80°C",
    },
    features: [
      "Compact Φ10.4 size",
      "Screw-fit mounting",
      "Reliable across temperature range",
      "Low maintenance design",
    ],
    torque: { min: 20, max: 300, unit: "gf.cm" },
    assembly_method: "Screw Fixing",
    buffer_direction: "bidirectional",
    durability: { cycles: 20000, cycles_unit: "cycles" },
    applications: ["Automotive interiors", "Household appliances", "Industrial machinery"],
    isActive: true,
    sortOrder: 7,
  },
  {
    slug: "rd-t025",
    model: "RD-T025",
    name: "Gear Damper RD-T025",
    category: "gear-damper",
    summary:
      "Widely applicable to automotive interiors, household appliances, industrial machinery, coffee machines, and printers.",
    description:
      "The RD-T025 gear damper is a versatile general-purpose rotary damper with Φ10.4 size and screw-fit mounting. Suitable for automotive, appliance, office equipment, coffee machine, and printer applications.",
    image: "/images/products/gear-damper/GearDamperSingle.webp",
    images: [],
    tech_params: { teeth_count: 10, module: 0.8, outer_diameter: "Φ10.4", pressure_angle: 20 },
    specifications: {
      "Torque Range": "20 – 300 gf·cm",
      "Operating Temperature": "-30°C to +80°C",
    },
    features: [
      "General-purpose rotary damper",
      "Screw-fit mounting",
      "Wide application compatibility",
      "Stable long-term performance",
    ],
    torque: { min: 20, max: 300, unit: "gf.cm" },
    assembly_method: "Screw Fixing",
    buffer_direction: "bidirectional",
    durability: { cycles: 20000, cycles_unit: "cycles" },
    applications: ["Automotive interiors", "Household appliances", "Coffee machines", "Printers"],
    isActive: true,
    sortOrder: 8,
  },
  {
    slug: "tad-18-axial-damper",
    model: "TAD-18",
    name: "TAD-18 Axial Damper",
    category: "axial-damper",
    summary: "Linear motion damper for push-pull and sliding applications.",
    description:
      "The TAD-18 axial damper provides controlled linear motion for applications requiring push-pull damping. Ideal for glove box doors, center console lids, and sliding mechanisms.",
    image: "/images/products/axial-damper/AxialDamperSingle.webp",
    images: [],
    tech_params: { outer_diameter: "12MM", total_height: "15.5MM" },
    specifications: {
      "Damping Force": "50 – 300 N",
      "Stroke Length": "20 – 80 mm",
      "Operating Temperature": "-30°C to +80°C",
      "Material": "Steel / POM",
      "Life Cycle": ">50,000 cycles",
    },
    features: [
      "Smooth linear damping action",
      "Adjustable damping force",
      "Compact axial design",
      "Push and pull configurations available",
    ],
    assembly_method: "Through-hole + Slot Fixing",
    buffer_direction: "bidirectional",
    durability: { cycles: 30000, cycles_unit: "cycles" },
    applications: ["Glove box doors", "Center console lids", "Sliding mechanisms"],
    isActive: true,
    sortOrder: 9,
  },
  {
    slug: "tgd-30-glove-box-damper",
    model: "TGD-30",
    name: "TGD-30 Glove Box Damper",
    category: "glove-box-damper",
    summary: "Soft-open mechanism for automotive glove boxes and storage compartments.",
    description:
      "The TGD-30 is specifically designed for automotive glove box applications, providing a premium soft-open feel. The integrated design ensures reliable performance across the vehicle's lifetime.",
    image: "/images/products/glove-box-damper/GloveBoxDamperSingle.webp",
    images: [],
    tech_params: { outer_diameter: "26.7MM", total_length: "105MM" },
    specifications: {
      "Damping Force": "80 – 250 N",
      "Operating Temperature": "-40°C to +85°C",
      "Material": "PA66 + GF / Steel",
      "Mounting Type": "Clip-in / Screw",
    },
    features: [
      "Premium soft-open feel",
      "Temperature-stable performance",
      "Quick installation design",
      "Validated to automotive durability standards",
    ],
    durability: { cycles: 20000, cycles_unit: "cycles" },
    applications: ["Automotive glove boxes", "Storage compartments"],
    isActive: true,
    sortOrder: 10,
  },
  {
    slug: "tl-12-push-latch",
    model: "TL-12",
    name: "TL-12 Push-Push Latch",
    category: "latch",
    summary: "Push-push latch mechanism for interior storage and access panels.",
    description:
      "The TL-12 push-push latch provides reliable lock/release functionality for automotive interior panels, storage compartments, and access doors. Designed for high-cycle durability.",
    image: "/images/products/latch/LatchSingle.webp",
    images: [],
    tech_params: { total_length: "11MM", total_width: "6.9MM", total_height: "17.6MM" },
    specifications: {
      "Latch Force": "15 – 50 N",
      "Operating Temperature": "-30°C to +80°C",
      "Material": "POM / Steel spring",
      "Life Cycle": ">100,000 cycles",
    },
    features: [
      "Push-push operation",
      "Compact form factor",
      "High cycle durability",
      "Corrosion-resistant components",
    ],
    hard_force: "6N",
    sound_type: "audible",
    durability: { cycles: 50000, cycles_unit: "cycles" },
    applications: ["Interior storage", "Access panels", "Automotive interior panels"],
    isActive: true,
    sortOrder: 11,
  },
  {
    slug: "tcm-custom-module",
    model: "TCM",
    name: "TCM Custom Damper Module",
    category: "other",
    summary: "Application-specific damper assemblies tailored to customer requirements.",
    description:
      "The TCM series represents TEAO's custom engineering capability. Each module is designed to customer specifications including torque, mounting, damping direction, and environmental requirements.",
    image: "/images/products/other/OthersSingle.webp",
    images: [],
    specifications: {
      "Torque Range": "Custom specified",
      "Configuration": "Per customer drawing",
      "Material": "Per application requirements",
      "Validation": "Per automotive standards",
    },
    features: [
      "Fully custom design",
      "Joint engineering support",
      "Rapid prototyping",
      "Scalable to mass production",
    ],
    applications: ["Custom applications"],
    isActive: true,
    sortOrder: 12,
  },
];

export const PARTNERS: Partner[] = [
  { name: "BYD", logo: "/images/partners/BYD.webp" },
  { name: "Geely", logo: "/images/partners/Geely.webp" },
  { name: "Chery", logo: "/images/partners/Chery.webp" },
  { name: "SAIC", logo: "/images/partners/SAIC.webp" },
  { name: "FAW", logo: "/images/partners/FAW.webp" },
  { name: "GAC", logo: "/images/partners/GAC.webp" },
  { name: "Changan", logo: "/images/partners/Changan.webp" },
  { name: "Great Wall", logo: "/images/partners/GreatWall.webp" },
  { name: "Dongfeng", logo: "/images/partners/Dongfeng.webp" },
  { name: "NIO", logo: "/images/partners/NIO.webp" },
  { name: "XPeng", logo: "/images/partners/XPeng.webp" },
  { name: "Li Auto", logo: "/images/partners/LiAuto.webp" },
];

export const SITE_CONFIG = {
  name: "TEAO",
  fullName: "Dongguan TEAO Electronic Technology Co., Ltd.",
  founded: 2001,
  email: "info@teao-damper.com",
  address:
    "No. 2, Huangjiang North Third Street, Huangjiang Town, Dongguan City, Guangdong Province (523750)",
  phone: "",
  social: {
    linkedin: env.LINKEDIN_URL,
    youtube: env.YOUTUBE_URL,
    facebook: env.FACEBOOK_URL,
    alibaba: env.ALIBABA_URL,
  },
};
