import type { Product, CategoryInfo, Partner } from "@/types";
import { env } from "./env";

export const CATEGORIES: CategoryInfo[] = [
  {
    slug: "gear-damper",
    name: "Gear Dampers",
    description: "Compact rotary control for cup holders, lids and storage doors.",
    image: "/images/products/gear-damper/GearDamperCategory.png",
  },
  {
    slug: "cylinder-damper",
    name: "Cylinder Dampers",
    description: "Linear damping for controlled opening, closing and sliding motion.",
    image: "/images/products/cylinder-damper/AxialDamperCategory.png",
  },
  {
    slug: "glove-box-damper",
    name: "Glove Box Dampers",
    description: "Automotive soft motion for glove boxes and interior panels.",
    image: "/images/products/glove-box-damper/GloveBoxDamperCategory.png",
  },
  {
    slug: "latch",
    name: "Latches",
    description: "Reliable lock, release and engagement mechanisms for interiors.",
    image: "/images/products/latch/LatchCategory.png",
  },
  {
    slug: "other",
    name: "Other Products",
    description: "Organizers, custom modules and application-specific mechanisms.",
    image: "/images/products/other/OthersCategory.png",
  },
];

export const PRODUCTS: Product[] = [
  {
    slug: "trd-25-rotary-gear-damper",
    name: "TRD-25 Rotary Gear Damper",
    category: "gear-damper",
    description: "High-torque rotary damper for automotive interior applications.",
    overview: "The TRD-25 series provides smooth, controlled rotary motion for automotive interior applications including cup holders, storage compartments, and assist handles. Available in multiple torque ranges with customizable mounting configurations.",
    image: "/images/products/gear-damper/GearDamperSingle.png",
    images: [],
    specifications: {
      "Torque Range": "0.5 – 4.0 N·m",
      "Operating Temperature": "-30°C to +80°C",
      "Material": "POM / PA66 + GF",
      "Damping Direction": "Clockwise / Counter-clockwise / Both",
      "Life Cycle": ">50,000 cycles",
    },
    features: [
      "Compact design fits tight interior spaces",
      "Stable torque output across temperature range",
      "Custom torque values available",
      "Low noise operation",
    ],
    isActive: true,
    sortOrder: 1,
  },
  {
    slug: "tad-18-axial-cylinder-damper",
    name: "TAD-18 Axial Cylinder Damper",
    category: "cylinder-damper",
    description: "Linear motion damper for push-pull and sliding applications.",
    overview: "The TAD-18 axial damper provides controlled linear motion for applications requiring push-pull damping. Ideal for glove box doors, center console lids, and sliding mechanisms.",
    image: "/images/products/cylinder-damper/AxialDamperSingle.png",
    images: [],
    specifications: {
      "Damping Force": "50 – 300 N",
      "Stroke Length": "20 – 80 mm",
      "Operating Temperature": "-30°C to +80°C",
      "Material": "Steel / POM",
      "Life Cycle": ">50,000 cycles",
    },
    features: [
      "Smooth linear damping action",
      "Adjustable damping force",
      "Compact cylinder design",
      "Push and pull configurations available",
    ],
    isActive: true,
    sortOrder: 2,
  },
  {
    slug: "tgd-30-glove-box-damper",
    name: "TGD-30 Glove Box Damper",
    category: "glove-box-damper",
    description: "Soft-open mechanism for automotive glove boxes and storage compartments.",
    overview: "The TGD-30 is specifically designed for automotive glove box applications, providing a premium soft-open feel. The integrated design ensures reliable performance across the vehicle's lifetime.",
    image: "/images/products/glove-box-damper/GloveBoxDamperSingle.png",
    images: [],
    specifications: {
      "Damping Force": "80 – 250 N",
      "Operating Temperature": "-40°C to +85°C",
      "Material": "PA66 + GF / Steel",
      "Mounting Type": "Clip-in / Screw",
    },
    features: [
      "Premium soft-open feel",
      "Temperature-stable performance",
      "Quick installation design",
      "Validated to automotive durability standards",
    ],
    isActive: true,
    sortOrder: 3,
  },
  {
    slug: "tl-12-push-latch",
    name: "TL-12 Push-Push Latch",
    category: "latch",
    description: "Push-push latch mechanism for interior storage and access panels.",
    overview: "The TL-12 push-push latch provides reliable lock/release functionality for automotive interior panels, storage compartments, and access doors. Designed for high-cycle durability.",
    image: "/images/products/latch/LatchSingle.png",
    images: [],
    specifications: {
      "Latch Force": "15 – 50 N",
      "Operating Temperature": "-30°C to +80°C",
      "Material": "POM / Steel spring",
      "Life Cycle": ">100,000 cycles",
    },
    features: [
      "Push-push operation",
      "Compact form factor",
      "High cycle durability",
      "Corrosion-resistant components",
    ],
    isActive: true,
    sortOrder: 4,
  },
  {
    slug: "tcm-custom-module",
    name: "TCM Custom Damper Module",
    category: "other",
    description: "Application-specific damper assemblies tailored to customer requirements.",
    overview: "The TCM series represents TEAO's custom engineering capability. Each module is designed to customer specifications including torque, mounting, damping direction, and environmental requirements.",
    image: "/images/products/other/OthersSingle.png",
    images: [],
    specifications: {
      "Torque Range": "Custom specified",
      "Configuration": "Per customer drawing",
      "Material": "Per application requirements",
      "Validation": "Per automotive standards",
    },
    features: [
      "Fully custom design",
      "Joint engineering support",
      "Rapid prototyping",
      "Scalable to mass production",
    ],
    isActive: true,
    sortOrder: 5,
  },
];

export const PARTNERS: Partner[] = [
  { name: "BYD", logo: "/images/partners/BYD.png" },
  { name: "Geely", logo: "/images/partners/Geely.png" },
  { name: "Chery", logo: "/images/partners/Chery.png" },
  { name: "SAIC", logo: "/images/partners/SAIC.png" },
  { name: "FAW", logo: "/images/partners/FAW.png" },
  { name: "GAC", logo: "/images/partners/GAC.png" },
  { name: "Changan", logo: "/images/partners/Changan.png" },
  { name: "Great Wall", logo: "/images/partners/GreatWall.png" },
  { name: "Dongfeng", logo: "/images/partners/Dongfeng.png" },
  { name: "NIO", logo: "/images/partners/NIO.png" },
  { name: "XPeng", logo: "/images/partners/XPeng.png" },
  { name: "Li Auto", logo: "/images/partners/LiAuto.png" },
];

export const SITE_CONFIG = {
  name: "TEAO",
  fullName: "Dongguan TEAO Electronic Technology Co., Ltd.",
  founded: 2001,
  email: "info@teao-damper.com",
  address: "No. 2, Huangjiang North Third Street, Huangjiang Town, Dongguan City, Guangdong Province (523750)",
  phone: "",
  social: {
    linkedin: env.LINKEDIN_URL,
    youtube: env.YOUTUBE_URL,
    facebook: env.FACEBOOK_URL,
    alibaba: env.ALIBABA_URL,
  },
};
